### ISSUE TITLE
How do I refer `src/css/font-face.css` for `custom` options?

### ISSUE THREAD

**Issue by ajmalafif** [escaladesports/gatsby-plugin-web-font-loader#4]
Hi,

Thanks so much for this plugin. It just works as plugin which is great. However, I am using `custom` font, and I can't seem to locate the `font-face.css`:

Config: https://github.com/ajmalafif/gatsby-tachyons-interUI/blob/master/gatsby-config.js#L12
CSS location: https://github.com/ajmalafif/gatsby-tachyons-interUI/blob/master/src/css/font-face.css
Demo: https://gatsby-tachyons-interui.netlify.com/ 

Appreciate any pointer or guidance. Thanks!

**Comment by kennedyrose** [comment]
I'm not as familiar with using the font loader with custom fonts. The plugin just uses [webfontloader](https://github.com/typekit/webfontloader) under the hood, so you should just be able to use the exact same options.

**Comment by cesar-gutierrez** [comment]
@ajmalafif Did you ever find a workaround for this? I'm having the same issue right now and haven't found a way to make it work. It's not finding the file cause it's not a production build path. I guess I could copy the file in the build directory but I'd rather take a cleaner approach.

![image](https://user-images.githubusercontent.com/22112130/48316610-5eafec00-e5bc-11e8-95a1-383f46064087.png)

**Comment by ajmalafif** [comment]
@cesar-gutierrez This one seems to work for me but I have no clue if this was working properly, you can check the commits from this repo here and try to deploy on netlify https://github.com/ajmalafif/gatsby-inter

**Comment by good-idea** [comment]
For those coming here with the same question, I have my setup working well like this:

```
   {
      resolve: 'gatsby-plugin-web-font-loader',
      options: {
        custom: {
          families: ['WPA LaPolice', 'WPA Akzidenz Grotesk:n4,n7'],
          urls: ['/fonts/fonts.css'],
        },
      },
    },
```

And with my directories looking like:

```
├── public
|   └── etc...
├── src
|   └── etc...
├── static
│   └── fonts
│       ├── AkzidenzGrotesk-Bold.otf
│       ├── AkzidenzGrotesk-Bold.woff
│       ├── AkzidenzGrotesk-Bold.woff2
│       └── fonts.css
├── tsconfig.json
├── tslint.json
└── yarn.lock
```
